[package]
name = "advent2019"
version = "0.1.0"
authors = ["Matt Long <matthewhl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "5.0.1"
failure = "0.1.6"
permutohedron = "0.2.4"